### ISSUE TITLE
Add support for background change

### ISSUE THREAD

**Issue by prudhomm** [feelpp/viewer#1]
background color should be configurable by the user using RGB code or colormap

**Comment by felixveysseyre** [comment]
Implemented

**Comment by prudhomm** [comment]
@felixveysseyre could you link this to a commit?

or better when you commit mention the issue #1  so that we can keep track of the development.

**Comment by felixveysseyre** [comment]
@prudhomm done.

But you will the changes only when I will have pushed to your repository.
