### ISSUE TITLE
Add support for camera position along axis 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/viewer#2]
it is currently possible only to reset the view, however it would be better to have the icons in paraview to set the Camera along the different axis or standard view instead of this reset menu entry

**Comment by felixveysseyre** [comment]
Front part implemented with commit f6fe514c27d7758933400e9e697c3ed369f97a1d

**Comment by felixveysseyre** [comment]
Back part implemented with commit 259d57f39c979f1c72526452375412ae9488a701

**Comment by prudhomm** [comment]
Where are the commits?

**Comment by felixveysseyre** [comment]
The commits will be pushed when step 2 will be complete.
