### ISSUE TITLE
Add support for axis 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/viewer#3]
There are currently no axis configuration, this should be configurable like in Paraview (there are different representation possible)

 - [x] Show grid
 - [x] axis title text, most of the time we don't change (space) but we have application where we need to change the axis title. 

Be careful with axis color and background color of the render view (should not be the same color ;))

**Comment by felixveysseyre** [comment]
Implemented with commit d93ea9e5bbc351cced1353d33f8ec745685bdb8a
