### ISSUE TITLE
Flexible architecture of the code

### ISSUE THREAD

**Issue by prudhomm** [feelpp/viewer#4]
As discussed with @vincentchabannes, we should have a flexible way to add remove entries in the menu interface through JSON files that would describe the actual interface.
Then we can configure the whole interface via JSON file depending on the final usage (medical doctor, engineer, student) and tailor the interface to the right end-user.

**Comment by felixveysseyre** [comment]
Implemented with commit 5e056e8cb4510311cdfbe8239fd582ce861f8cf2
