### ISSUE TITLE
Add support for legend and colormap

### ISSUE THREAD

**Issue by prudhomm** [feelpp/viewer#5]
The legend cannot be moved at the moved neither configured 
 * change the text of the legend
 * move the legend and allow vertical/horizontal layout
 * change the colormap (eg rainbow,...)

 - [x] reset data range
 - [x] rescale data rage
 - [x] log scale
 - [x] change color map preset (take first 5: and among them rainbow)

/cc @vincentchabannes

**Comment by felixveysseyre** [comment]
Implemented with commits: e19a2aa11967c7b719d8222221cd1ec7079dc5a6, f535c776c3a0652be6d8c96ef19254398b5827ed, 1047453c7edbef735dc370fc58173f1dd01d79ca, 13f6187f6b2eeb4769c6c655b890c9d3e2533945
